version: '3.7'

services:

  create-react-app:
    container_name: create-react-app
    build:
      context: ./examples/create-react-app
      dockerfile: ./Dockerfile
    command: bash -c "npm start"
    volumes:
      - './examples/create-react-app:/app'
      # We are specifying an anonymous volume here so that our local node_modules directory does not override node_modules installed in our container
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
